@extends('layouts.store')
@section('title','سبد خرید | PALAZ ONLINE')
@section('content')
<section class="page-head cart-head"><div class="container"><span class="eyebrow">PALAZ ONLINE / CART</span><h1>سبد خرید</h1><p>انتخاب‌های شما در یک مسیر؛ خدمات اجرا را هم می‌توانید به پروژه اضافه کنید.</p></div></section>
<section class="section cart-section"><div class="container">@if($items->isEmpty())
<div class="empty large cart-empty"><span>◌</span><h2>سبد خرید خالی است</h2><p>هنوز محصولی انتخاب نکرده‌اید. مجموعه پالاز را ببینید و مسیرتان را شروع کنید.</p><a class="btn btn-primary" href="{{ route('shop') }}">رفتن به فروشگاه <b>←</b></a></div>
@else
<div class="cart-layout"><main><div class="cart-top"><strong>{{ $items->sum('quantity') }} عدد در {{ count($items) }} انتخاب</strong><a href="{{ route('shop') }}">← ادامه خرید</a></div><div class="cart-list">@foreach($items as $item)<article class="cart-row-new"><a class="cart-product" href="{{ route('product',$item['id']) }}"><div class="mini-visual {{ $item['tone'] }}"><b>PALAZ</b></div><div><small>{{ strtoupper($item['category']) }} / COLLECTION</small><strong>{{ $item['name'] }}</strong><span>{{ $item['unit'] }}</span></div></a><div class="cart-qty"><small>تعداد</small><b>{{ $item['quantity'] }}</b></div><div class="cart-price"><small>قیمت</small><b>محاسبه هنگام سفارش</b></div><a class="cart-remove" href="{{ route('product',$item['id']) }}">مشاهده محصول</a></article>@endforeach</div>
<div class="cart-services"><div><span class="eyebrow">ADD A SERVICE</span><h3>پروژه را کامل کنید</h3><p>اگر خرید شما برای یک فضای واقعی است، خدمات موردنیاز را همین حالا به مسیر اضافه کنید.</p></div><div class="cart-service-links"><a href="{{ route('services',['type'=>'measurement']) }}"><b>⌖ اندازه‌گیری</b><small>ارسال به DTZ ←</small></a><a href="{{ route('services',['type'=>'installation']) }}"><b>⌂ نصب</b><small>درخواست خدمات ←</small></a><a href="{{ route('services',['type'=>'design']) }}"><b>◇ طراحی</b><small>DTZ Tablet ←</small></a></div></div>
</main><aside class="cart-summary"><span class="eyebrow">ORDER SUMMARY</span><h2>خلاصه سفارش</h2><div class="summary-line"><span>محصولات</span><b>{{ count($items) }} مورد</b></div><div class="summary-line"><span>خدمات</span><b>انتخاب در مرحله بعد</b></div><div class="summary-line total"><span>مبلغ</span><b>محاسبه نهایی</b></div><a class="btn btn-primary wide" href="{{ route('services') }}">ادامه به اطلاعات سفارش <span>←</span></a><small class="summary-note">قیمت نهایی، متراژ و خدمات موردنیاز قبل از ثبت سفارش مشخص می‌شود.</small></aside></div>
@endif</div></section>
@endsection