@extends('layouts.store')
@section('title','PALAZ ONLINE | خانه')
@section('content')
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><div class="hero-kicker"><span class="eyebrow">PALAZ ONLINE / NEW ERA</span><span class="hero-number">01 — 03</span></div><h1>خانه‌ای که<br><em>با انتخاب شما</em><br>ساخته می‌شود.</h1><p>محصول را انتخاب کنید، مشاوره بگیرید و اگر پروژه نیاز دارد، اندازه‌گیری، طراحی و نصب را هم در همان مسیر انجام دهید.</p><div class="hero-live-badge"><span></span> تجربه خرید تا اجرا، یک مسیر متصل</div><div class="hero-buttons"><a class="btn btn-primary" href="{{ route('shop') }}">شروع خرید <span>←</span></a><a class="btn btn-ghost" href="{{ route('services') }}">مشاوره خرید</a></div><div class="hero-trust"><span><b>01</b> اصالت کالا</span><span><b>02</b> مشاوره تخصصی</span><span><b>03</b> خدمات اجرا</span></div></div><div class="hero-art" data-hero-art><div class="hero-cursor-glow"></div><div class="hero-slides" aria-label="تصاویر محصولات پالاز"><div class="hero-slide hero-slide-one is-active" data-kicker="PALAZ / LIVING" data-title="گرمایی که<br>از کف شروع می‌شود." data-note="موکت‌های منتخب برای فضاهای گرم و ماندگار."></div><div class="hero-slide hero-slide-two" data-kicker="PALAZ / FLOOR" data-title="جزئیات فضا<br>را کامل کنید." data-note="انتخاب‌های هماهنگ برای خانه‌ای با هویت."></div><div class="hero-slide hero-slide-three" data-kicker="PALAZ / DESIGN" data-title="انتخاب امروز،<br>شروع پروژه فرداست." data-note="از محصول تا اندازه‌گیری و اجرا، یک مسیر متصل."></div></div><div class="art-grid"></div><div class="art-label">DESIGNED<br><strong>FOR LIVING</strong></div><div class="hero-slide-dots" aria-hidden="true"><span class="active"></span><span></span><span></span></div><div class="hero-slide-progress" aria-hidden="true"><span></span></div><div class="hero-art-meta"><b data-hero-kicker>PALAZ / LIVING</b><span>COLLECTION · LIVING</span></div><div class="hero-art-caption"><span data-hero-note>موکت‌های منتخب برای فضاهای گرم و ماندگار.</span><strong data-hero-title>گرمایی که<br>از کف شروع می‌شود.</strong></div><div class="hero-floating-card"><span>CURATED FOR YOU</span><strong>از انتخاب<br>تا اجرا</strong><small>یک مسیر متصل با PALAZ</small></div><div class="hero-bottom-label"><span>01</span><i></i><span>03</span></div></div></div></section>
<section class="section intro-section"><div class="container intro-grid"><div><span class="eyebrow">THE PALAZ WAY</span><h2>فقط فروشگاه نیستیم.<br><em>مسیر پروژه را می‌سازیم.</em></h2></div><p>از یک رول موکت تا یک پروژه کامل، اطلاعات و خدمات لازم باید کنار هم باشند. PALAZ ONLINE نقطه شروع این مسیر است و DTZ و DTZ Tablet ادامه آن.</p></div></section>
<section class="section category-section"><div class="container"><div class="section-head category-section-head"><div><span class="eyebrow">EXPLORE COLLECTIONS</span><h2>فضای خودتان را انتخاب کنید</h2><p>از کف تا دیوار، مجموعه‌های پالاز را بر اساس سبک فضای خودتان کشف کنید.</p></div><a href="{{ route('shop') }}">همه محصولات <span>←</span></a></div><div class="category-grid">@foreach($categories as $key=>$category)<a class="category-card category-{{ $key }} {{ $category['tone'] }}" href="{{ route('shop',['category'=>$key]) }}"><span class="category-index">{{ sprintf('%02d',$loop->iteration) }}</span><div class="category-glow"></div><div class="category-copy"><span class="category-eyebrow">{{ $category['eyebrow'] }}</span><strong>{{ $category['title'] }}</strong><b>کشف مجموعه <i>←</i></b></div><span class="category-arrow">↗</span></a>@endforeach</div></div></section>
<section class="service-section" id="journey"><div class="container"><div class="section-head light"><div><span class="eyebrow">ONE CONNECTED JOURNEY</span><h2>خرید فقط شروع کار است</h2><p class="journey-lead">یک پروژه، چند ابزار تخصصی؛ اما برای شما فقط یک مسیر.</p></div><span class="section-note">PALAZ ONLINE → DTZ → DTZ TABLET → EXECUTION</span></div><div class="journey-rail" aria-hidden="true"><span class="journey-line"></span><span class="journey-node">PALAZ</span><span class="journey-node">DTZ</span><span class="journey-node">TABLET</span><span class="journey-node">EXECUTION</span></div><div class="service-grid connected-grid">
<a href="{{ route('services',['type'=>'measurement']) }}" class="service-card"><span class="service-index">01</span><span class="service-icon">⌖</span><div><span class="service-step">01 / DTZ</span><h3>اندازه‌گیری دقیق</h3><p>برای پروژه‌هایی که متراژ واقعی و موقعیت اجرا باید مشخص شود.</p><small>ثبت درخواست <b>←</b></small></div></a>
<a href="{{ route('services',['type'=>'installation']) }}" class="service-card"><span class="service-index">02</span><span class="service-icon">⌂</span><div><span class="service-step">02 / DTZ</span><h3>نصب حرفه‌ای</h3><p>درخواست نصب در مسیر اجرایی پالاز قرار می‌گیرد.</p><small>شروع درخواست <b>←</b></small></div></a>
<a href="{{ route('services',['type'=>'design']) }}" class="service-card"><span class="service-index">03</span><span class="service-icon">◇</span><div><span class="service-step">03 / TABLET</span><h3>طراحی و محاسبه</h3><p>پلان، اندازه‌ها و محاسبات پروژه وارد مسیر DTZ Tablet می‌شود.</p><small>شروع پروژه <b>←</b></small></div></a>
</div></div></section>
<section class="section product-section"><div class="container"><div class="section-head"><div><span class="eyebrow">PALAZ COLLECTION</span><h2>محصولات منتخب</h2></div><a href="{{ route('shop') }}">مشاهده فروشگاه ←</a></div><div class="product-grid">@foreach($products as $index=>$product)<article class="product-card"><a href="{{ route('product',$product['id']) }}"><div class="product-visual product-{{ $product['category'] }} {{ $product['tone'] }}"><span>{{ sprintf('%02d',$index+1) }}</span><b>PALAZ</b></div><div class="product-info"><small>{{ strtoupper($product['category']) }} / COLLECTION</small><h3>{{ $product['name'] }}</h3><p>{{ $product['unit'] }}</p><strong>مشاهده محصول <i>←</i></strong></div></a></article>@endforeach</div></div></section>
<section class="project-banner"><div class="container project-grid"><div><span class="eyebrow">FROM IDEA TO INSTALLATION</span><h2>پروژه‌تان را دارید؟<br><em>از همین‌جا شروع کنید.</em></h2><p>نوع خدمت را انتخاب کنید؛ اطلاعات لازم را بفرستید و ادامه مسیر را به سیستم تخصصی مربوطه بسپارید.</p></div><div class="project-actions project-actions-enhanced"><a href="{{ route('services',['type'=>'measurement']) }}">اندازه‌گیری <span>DTZ</span><b>←</b></a><a href="{{ route('services',['type'=>'design']) }}">طراحی و محاسبه <span>DTZ TABLET</span><b>←</b></a><a href="{{ route('services',['type'=>'installation']) }}">نصب <span>DTZ</span><b>←</b></a></div></div></section>
@endsection