@extends('layouts.store')
@section('title','PALAZ ONLINE | خانه')
@section('content')
<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">PALAZ ONLINE / 01</span><h1>خانه‌ای که<br><em>با انتخاب شما</em><br>ساخته می‌شود.</h1><p>محصول، مشاوره، اندازه‌گیری و نصب؛ از اولین انتخاب تا اجرای نهایی در یک مسیر ساده و حرفه‌ای.</p><div class="hero-buttons"><a class="btn btn-primary" href="{{ route('shop') }}">مشاهده محصولات</a><a class="btn btn-ghost" href="{{ route('services') }}">مشاوره خرید ←</a></div><div class="hero-trust"><span>✓ اصالت کالا</span><span>✓ مشاوره تخصصی</span><span>✓ پیگیری سفارش</span></div></div><div class="hero-art"><div class="art-card art-one"></div><div class="art-card art-two"></div><div class="art-card art-three"></div><div class="art-caption">DESIGNED<br>FOR LIVING</div></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">EXPLORE</span><h2>دسته‌بندی‌ها</h2></div><a href="{{ route('shop') }}">مشاهده همه ←</a></div><div class="category-grid">@foreach($categories as $key=>$category)<a class="category-card {{ $category['tone'] }}" href="{{ route('shop',['category'=>$key]) }}"><span>{{ $category['eyebrow'] }}</span><strong>{{ $category['title'] }}</strong><b>مشاهده ←</b></a>@endforeach</div></div></section>
<section class="service-section"><div class="container"><div class="section-head light"><div><span class="eyebrow">CONNECTED SERVICES</span><h2>خرید فقط شروع کار است</h2></div></div><div class="service-grid">
<a href="{{ route('services',['type'=>'measurement']) }}" class="service-card"><span class="service-icon">⌖</span><div><h3>اندازه‌گیری دقیق</h3><p>درخواست اندازه‌گیری آماده ارسال به DTZ است.</p><small>شروع درخواست ←</small></div></a>
<a href="{{ route('services',['type'=>'installation']) }}" class="service-card"><span class="service-icon">⌂</span><div><h3>نصب حرفه‌ای</h3><p>هماهنگی اجرای پروژه در مسیر خدمات پالاز.</p><small>شروع درخواست ←</small></div></a>
<a href="{{ route('services',['type'=>'design']) }}" class="service-card"><span class="service-icon">◇</span><div><h3>طراحی و محاسبه</h3><p>پلان و محاسبات پروژه برای DTZ Tablet آماده می‌شود.</p><small>شروع پروژه ←</small></div></a>
</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="eyebrow">SELECTED</span><h2>محصولات منتخب</h2></div><a href="{{ route('shop') }}">فروشگاه ←</a></div><div class="product-grid">@foreach($products as $product)<article class="product-card"><a href="{{ route('product',$product['id']) }}"><div class="product-visual {{ $product['tone'] }}"><span>PALAZ</span></div><div class="product-info"><small>PALAZ COLLECTION</small><h3>{{ $product['name'] }}</h3><p>{{ $product['unit'] }}</p><strong>جزئیات محصول ←</strong></div></a></article>@endforeach</div></div></section>
<section class="process"><div class="container process-grid"><div><span class="eyebrow">ONE CONNECTED JOURNEY</span><h2>از انتخاب تا اجرا، بدون گم‌شدن بین سیستم‌ها.</h2></div><div class="process-steps"><div><b>01</b><span>انتخاب محصول</span></div><div><b>02</b><span>خدمات موردنیاز</span></div><div><b>03</b><span>DTZ / Tablet</span></div><div><b>04</b><span>اجرای پروژه</span></div></div></div></section>
@endsection
