@extends('layouts.store')
@section('title',$product['name'].' | PALAZ ONLINE')
@section('content')
<section class="product-detail product-detail-new"><div class="container detail-grid"><div class="detail-visual-wrap"><div class="detail-visual product-detail-{{ $product['category'] }} {{ $product['tone'] }}" data-product-image><span>PALAZ</span><small>PALAZ COLLECTION / {{ strtoupper(substr($product['id'], -2)) }}</small></div><div class="visual-thumbs"><span class="{{ $product['tone'] }}"></span><span class="tone-dark"></span><span class="tone-light"></span></div></div><div class="detail-copy"><div class="detail-breadcrumb"><a href="{{ route('shop') }}">فروشگاه</a><span>/</span><span>{{ $product['category'] }}</span></div><span class="eyebrow">{{ strtoupper($product['category']) }} / COLLECTION</span><h1>{{ $product['name'] }}</h1><p class="lead">{{ $product['description'] }}</p><div class="detail-rating"><span>★★★★★</span><small>محصول منتخب پالاز</small></div><div class="detail-box"><div><small>واحد فروش</small><strong>{{ $product['unit'] }}</strong></div><div><small>نوع محصول</small><strong>{{ $product['category'] }}</strong></div></div>
<form method="POST" action="{{ route('cart.add',$product['id']) }}" class="product-buy-form">@csrf
<div class="option-block"><label>رنگ / مدل</label><div class="swatches"><button type="button" class="swatch selected tone-a" data-visual="tone-a" aria-label="رنگ ۱"></button><button type="button" class="swatch tone-b" data-visual="tone-b" aria-label="رنگ ۲"></button><button type="button" class="swatch tone-c" data-visual="tone-c" aria-label="رنگ ۳"></button><button type="button" class="swatch tone-d" data-visual="tone-d" aria-label="رنگ ۴"></button></div></div>
<div class="buy-row"><div class="quantity"><button type="button" onclick="this.nextElementSibling.stepDown()">−</button><input type="number" name="quantity" value="1" min="1"><button type="button" onclick="this.previousElementSibling.stepUp()">+</button></div><button class="btn btn-primary buy-btn" type="submit">افزودن به سبد خرید <span>←</span></button></div></form>
@if($product['category'] === 'موکت')
<div class="mb-3"><a class="btn btn-outline-dark w-100" href="{{ route('calculator.show', $product['id']) }}">محاسبه فروش طاقه عرض ۳ متر ←</a></div>
@endif
<div class="project-options"><div><span>⌖</span><a href="{{ route('services',['type'=>'measurement']) }}"><b>نیاز به اندازه‌گیری؟</b><small>درخواست را به DTZ بفرستید ←</small></a></div><div><span>◇</span><a href="{{ route('services',['type'=>'design']) }}"><b>نیاز به محاسبه یا طراحی؟</b><small>شروع پروژه در DTZ Tablet ←</small></a></div><div><span>⌂</span><a href="{{ route('services',['type'=>'installation']) }}"><b>نیاز به نصب دارید؟</b><small>درخواست خدمات نصب ←</small></a></div></div>
</div></div></section>
<section class="section detail-info-section"><div class="container detail-info-grid"><div><span class="eyebrow">ABOUT THE PRODUCT</span><h2>انتخابی برای فضای شما</h2><p>قبل از خرید می‌توانید از مشاوره تخصصی استفاده کنید و در صورت نیاز، مسیر اندازه‌گیری، طراحی و نصب را هم به سفارش خود اضافه کنید.</p></div><div class="spec-table"><div><span>کد محصول</span><b>PLZ-{{ strtoupper(substr($product['id'], -6)) }}</b></div><div><span>دسته‌بندی</span><b>{{ $product['category'] }}</b></div><div><span>خدمات قابل درخواست</span><b>اندازه‌گیری / طراحی / نصب</b></div><div><span>مسیر اجرا</span><b>PALAZ ONLINE → DTZ</b></div></div></div></section>
<section class="section compact"><div class="container feature-strip"><div><b>01</b><span>مشاوره تخصصی</span></div><div><b>02</b><span>اندازه‌گیری</span></div><div><b>03</b><span>محاسبه پروژه</span></div><div><b>04</b><span>نصب حرفه‌ای</span></div></div></section>
@endsection