@extends('layouts.store')
@section('title','خدمات | PALAZ ONLINE')
@section('content')
<section class="page-head services-head"><div class="container"><span class="eyebrow">PALAZ ONLINE / SERVICES</span><h1>خرید، فقط محصول نیست.</h1><p>هرجا پروژه نیاز به اندازه‌گیری، طراحی یا اجرا داشته باشد، مسیر خدمات از همین‌جا شروع می‌شود.</p></div></section>
<section class="section services-page"><div class="container"><div class="services-intro"><div><span class="eyebrow">CHOOSE YOUR PATH</span><h2>سه مسیر، یک تجربه متصل</h2></div><p>درخواست شما ابتدا در PALAZ ONLINE ثبت می‌شود و در معماری نهایی به سیستم تخصصی مربوطه منتقل خواهد شد.</p></div><div class="service-choice-grid">
<a class="service-choice-card {{ request('type')==='measurement'?'chosen':'' }}" href="{{ route('services',['type'=>'measurement']) }}"><span class="service-big">⌖</span><div><small>01 / DTZ</small><h3>اندازه‌گیری دقیق</h3><p>برای زمانی که متراژ واقعی، موقعیت و شرایط اجرای پروژه باید مشخص شود.</p><b>شروع درخواست ←</b></div></a>
<a class="service-choice-card {{ request('type')==='installation'?'chosen':'' }}" href="{{ route('services',['type'=>'installation']) }}"><span class="service-big">⌂</span><div><small>02 / DTZ</small><h3>نصب حرفه‌ای</h3><p>درخواست اجرای پروژه و هماهنگی مراحل نصب در مسیر خدمات پالاز.</p><b>شروع درخواست ←</b></div></a>
<a class="service-choice-card {{ request('type')==='design'?'chosen':'' }}" href="{{ route('services',['type'=>'design']) }}"><span class="service-big">◇</span><div><small>03 / DTZ TABLET</small><h3>طراحی و محاسبه</h3><p>پلان و محاسبات پروژه برای ادامه کار در DTZ Tablet آماده می‌شود.</p><b>شروع پروژه ←</b></div></a>
</div></div></section>
<section class="section request-section"><div class="container request-layout"><div class="request-side"><span class="eyebrow">REQUEST / {{ strtoupper(request('type','measurement')) }}</span><h2>اطلاعات پروژه را بفرستید.</h2><p>بعد از ثبت، یک کد پیگیری دریافت می‌کنید. اتصال API به DTZ و DTZ Tablet در مرحله Integration فعال خواهد شد.</p><div class="request-flow"><span><b>01</b>ثبت اطلاعات</span><i>→</i><span><b>02</b>ساخت درخواست</span><i>→</i><span><b>03</b>مسیر تخصصی</span></div></div><form class="request-form request-form-new" method="POST" action="{{ route('services.request') }}">@csrf<div class="form-head"><span class="eyebrow">START PROJECT</span><h2>شروع درخواست</h2></div><label>نوع درخواست<select name="type" required><option value="measurement" @selected(request('type','measurement')==='measurement')>اندازه‌گیری</option><option value="installation" @selected(request('type')==='installation')>نصب</option><option value="design" @selected(request('type')==='design')>طراحی و محاسبه</option></select></label><div class="form-two"><label>نام و نام خانوادگی<input name="name" required placeholder="نام شما"></label><label>شماره تماس<input name="phone" required placeholder="09xxxxxxxxx" inputmode="tel"></label></div><label>توضیحات پروژه<textarea name="description" rows="5" placeholder="متراژ، آدرس، نوع فضا یا هر توضیحی که به شروع پروژه کمک می‌کند..."></textarea></label><label class="consent"><input type="checkbox" required> <span>با ثبت این درخواست، اطلاعات برای پیگیری خدمات استفاده می‌شود.</span></label><button class="btn btn-primary wide">ثبت درخواست و دریافت کد پیگیری <span>←</span></button></form></div></section>
<section class="service-bottom"><div class="container"><span>PALAZ ONLINE</span><strong>یک ورودی برای تمام مسیرهای پروژه.</strong><a href="{{ route('shop') }}">بازگشت به فروشگاه ←</a></div></section>
@endsection